Added functionality to locating password

diff --git a/password b/password
--- a/password
+++ b/password
@@ -25,14 +25,16 @@ pick_random_char() {
     fi
 }
 
+# helper char function, picks random special character
 pick_random_special_char() {
-    special_char=('!' '@' '*' '$' '?' '#')
-    local i=$(shuf -i 1-6 -n 1)
+    special_char=('!' '$' '?' '#')
+    local i=$(shuf -i 1-4 -n 1)
     random_special_char=${special_char[i]}
 }
 
+# creates password
 generate_password() {
-    another_random_int=$(shuf -i 0-1 -n 1) # random integer, either 0 or 1
+    local another_random_int=$(shuf -i 0-1 -n 1) # random integer, either 0 or 1
     pick_random_char $another_random_int
     password+=$random_char
 
@@ -51,9 +53,11 @@ generate_password() {
     pick_random_int
     password+=$random_int
 
+    local another_random_int=$(shuf -i 0-1 -n 1)
     pick_random_char $another_random_int
     password+=$random_char
 
+    local another_random_int=$(shuf -i 0-1 -n 1)
     pick_random_char $another_random_int
     password+=$random_char
 
@@ -61,12 +65,26 @@ generate_password() {
     password+=$random_special_char
 }
 
-while getopts ":chf:" option; do
-    case ${option} in 
+while getopts ":c:hf:" option; do
+    case $option in 
         c)  # create password
-            # echo -e "\tPassword: $(date | md5sum | head -c 10)"
+            # storing password in passwords.txt
+            if grep -q "$2" passwords.txt; then
+                echo -e "\tError: duplicate label called '$2' found"
+                exit 1
+            fi
+
             generate_password
-            echo -e "\tPassword: ${password[@]}"
+            echo -e "\t$2 Password: ${password[@]}"
+            echo -e "$2,${password[@]}" >> passwords.txt   # writing password to passwords.txt
+
+            # creating file for where all passwords are stored
+            if [[ ! -f "passwords.txt" ]]; then   # if cannot find passwords.txt, create and set permissions
+                touch passwords.txt
+                chmod u+r passwords.txt
+            else    # else ensure permissions are set to prevent tampering
+                chmod u+r passwords.txt # change later
+            fi
             ;;
         h)  # help     
             echo -e "\tGenerate or locate password"
@@ -78,12 +96,22 @@ while getopts ":chf:" option; do
             echo -e "\tf    Find previously generated password"
             ;;
         f)  # finding password
-            echo "finding"
+            while IFS= read -r line; do
+                if grep -q "$2" passwords.txt; then
+                    echo -e "\t$2 Password: $(cut -d "," -f2 <<< $line)"
+                    break
+                fi
+            done < "/Users/kids/Desktop/bash/passwords.txt"
             ;;
         *)  # default
             echo -e "\tpassword: illegal option -- "${1:1}""
-            echo -e "\tusage: password [-c] [SEED]"
+            echo -e "\tusage: password [-c] [LABEL]"
             echo -e "\tusage: password [-hf]"
+
+            echo -e "\n\tExamples:"
+            echo -e "\tpassword -c Facebook        Generates password with 'Facebook' label"
+            echo -e "\tpassword -h                 Display help"
+            echo -e "\tpassword -f Facebook        Returns password with 'Facebook' label"
             exit 1
             ;;
         esac
