Added "force remove" option and functionality

diff --git a/password b/password
--- a/password
+++ b/password
@@ -7,14 +7,14 @@ random_special_char='!'
 declare -a password
 # end of global data
 
-# helper int function w/ no parameters, picks random number from 0 to 9 (inclusive)
-pick_random_int() {
+# helper int function w/ no parameters, picks random number from 0 to 9
+set_random_int() {
     random_int=$(shuf -i 0-9 -n 1)    
 }
 
 # helper char function, picks random letter
 # if first arg is true, then returns upper case char
-pick_random_char() {
+set_random_char() {
     local i=$(shuf -i 1-26 -n 1)   # picks random number from 1 to 26
     lower_case=(a b c d e f g h i j k l m n o p q r s t u v w x y z)
     upper_case=(A B C D E F G H I J K L M N O P Q R S T U V W X Y Z)
@@ -26,7 +26,7 @@ pick_random_char() {
 }
 
 # helper char function, picks random special character
-pick_random_special_char() {
+set_random_special_char() {
     special_char=('!' '$' '?' '#')
     local i=$(shuf -i 1-4 -n 1)
     random_special_char=${special_char[i]}
@@ -35,26 +35,26 @@ pick_random_special_char() {
 # creates password
 generate_password() {
     local another_random_int=$(shuf -i 0-1 -n 1) # random integer, either 0 or 1
-    pick_random_char $another_random_int
+    set_random_char $another_random_int
     password+=$random_char
 
     for (( i=0; i<5; i++ )); do
-        pick_random_int
+        set_random_int
         password+=$random_int
     done
 
     for (( i=0; i<2; i++ )); do
         local another_random_int=$(shuf -i 0-1 -n 1)
-        pick_random_char $another_random_int
+        set_random_char $another_random_int
         password+=$random_char
     done
 
-    pick_random_special_char
+    set_random_special_char
     password+=$random_special_char
 }
 
 path=$(find . -name passwords.txt)  # getting path to passwords.txt
-while getopts ":c:hf:ar:" option; do
+while getopts ":c:hf:ar:R" option; do
     case $option in 
         c)  # create password            
             if [[ ! -f "passwords.txt" ]]; then   # if cannot find passwords.txt, create and set permissions
@@ -86,7 +86,7 @@ while getopts ":c:hf:ar:" option; do
         h)  # help     
             echo -e "\tGenerate or locate password"
             echo
-            echo -e "\tSyntax: password [-chf]"
+            echo -e "\tSyntax: password [-chfarf] [LABEL]"
             echo -e "\toptions:"
             echo -e "\tc    Create password with some hash algorithm"
             echo -e "\th    Display help page"
@@ -118,11 +118,36 @@ while getopts ":c:hf:ar:" option; do
                     echo -e "\tSuccessfully removed password for '$2'"
                     break;
                 elif [[ line_count -eq max_lines ]]; then    # TO DO: FIX
-                    echo -e "\tError: cannot find and reomve label '$2'"
-                    break;
+                    echo -e "\tError: cannot find and remove label '$2'"
+                    exit 1
                 fi
                 line_count=$((line_count+1))  # line count
             done < $path
+            ;;
+        R) # force remove all passwords
+            echo -en "\tForce remove passwords.txt file [y/n]: "
+            read user_input
+            if [[ $user_input == "y" ]]; then   # if user input is yes,
+                case `find . -name 'passwords.txt' > /dev/null; echo $?` in
+                    0) # cannot locate passwords.txt
+                        echo -e "\n\tError: cannot find passwords.txt"
+                        exit 1
+                        ;;
+                    1)  # successfully able to find passwords.txt
+                        rm passwords.txt
+                        echo -e "\tSuccessfully removed passwords.txt"
+                        ;;
+                    *)  # default error
+                        echo -e "\tError: type unknown"
+                        exit 1
+                        ;;
+                esac
+            elif [[ $user_input == "n" ]]; then
+                echo -e "\tExiting..."
+            else
+                echo -e "\tError: please input valid response"
+                exit 1
+            fi
             ;;
         *)  # default
             echo -e "\tpassword: illegal option -- "$@""
