Added error handling for finding password
Fixed some minor bugs as well

diff --git a/password b/password
--- a/password
+++ b/password
@@ -38,28 +38,16 @@ generate_password() {
     pick_random_char $another_random_int
     password+=$random_char
 
-    pick_random_int
-    password+=$random_int
+    for (( i=0; i<5; i++ )); do
+        pick_random_int
+        password+=$random_int
+    done
 
-    pick_random_int
-    password+=$random_int
-
-    pick_random_int
-    password+=$random_int
-
-    pick_random_int
-    password+=$random_int
-
-    pick_random_int
-    password+=$random_int
-
-    local another_random_int=$(shuf -i 0-1 -n 1)
-    pick_random_char $another_random_int
-    password+=$random_char
-
-    local another_random_int=$(shuf -i 0-1 -n 1)
-    pick_random_char $another_random_int
-    password+=$random_char
+    for (( i=0; i<2; i++ )); do
+        local another_random_int=$(shuf -i 0-1 -n 1)
+        pick_random_char $another_random_int
+        password+=$random_char
+    done
 
     pick_random_special_char
     password+=$random_special_char
@@ -69,15 +57,7 @@ while getopts ":c:hf:" option; do
     case $option in 
         c)  # create password
             # storing password in passwords.txt
-            if grep -q "$2" passwords.txt; then
-                echo -e "\tError: duplicate label called '$2' found"
-                exit 1
-            fi
-
-            generate_password
-            echo -e "\t$2 Password: ${password[@]}"
-            echo -e "$2,${password[@]}" >> passwords.txt   # writing password to passwords.txt
-
+            
             # creating file for where all passwords are stored
             if [[ ! -f "passwords.txt" ]]; then   # if cannot find passwords.txt, create and set permissions
                 touch passwords.txt
@@ -85,6 +65,25 @@ while getopts ":c:hf:" option; do
             else    # else ensure permissions are set to prevent tampering
                 chmod u+r passwords.txt # change later
             fi
+
+            # checking for duplicate labels in passwords.txt
+            # if duplicate label found, print error
+            # else do nothing
+            case `grep "$2" passwords.txt > /dev/null; echo $?` in
+                0) # success, no duplicate labels found in file
+                    echo -e "\tError: duplicate label called '$2' found"
+                    exit 1
+                    ;;
+                1) # error, found duplicate in file
+                    generate_password
+                    echo -e "\t$2 Password: ${password[@]}"
+                    echo -e "$2,${password[@]}" >> passwords.txt   # writing password to passwords.txt
+                    ;;
+                *)
+                    echo "\tError: type unknown"
+                    exit 1
+                    ;;
+            esac
             ;;
         h)  # help     
             echo -e "\tGenerate or locate password"
@@ -97,10 +96,18 @@ while getopts ":c:hf:" option; do
             ;;
         f)  # finding password
             while IFS= read -r line; do
-                if grep -q "$2" passwords.txt; then
-                    echo -e "\t$2 Password: $(cut -d "," -f2 <<< $line)"
-                    break
-                fi
+                case `grep "$2" passwords.txt > /dev/null; echo $?` in
+                    0)  # if find arg in file
+                        label=$(cut -d "," -f1 <<< $line)   # gets substring before comma
+                        pass=$(cut -d "," -f2 <<< $line)    # gets substring after comma
+                        echo -e "\t$label Password: $pass"
+                        break
+                        ;;
+                    *)  # if unable to find arg in file
+                        echo -e "\tError: cannot find password for '$2'"
+                        exit 1
+                        ;;
+                esac
             done < "/Users/kids/Desktop/bash/passwords.txt"
             ;;
         *)  # default
