Added new branch called "remove"

diff --git a/password b/password
--- a/password
+++ b/password
@@ -25,48 +25,64 @@ pick_random_char() {
     fi
 }
 
+# helper char function, picks random special character
 pick_random_special_char() {
-    special_char=('!' '@' '*' '$' '?' '#')
-    local i=$(shuf -i 1-6 -n 1)
+    special_char=('!' '$' '?' '#')
+    local i=$(shuf -i 1-4 -n 1)
     random_special_char=${special_char[i]}
 }
 
+# creates password
 generate_password() {
-    another_random_int=$(shuf -i 0-1 -n 1) # random integer, either 0 or 1
+    local another_random_int=$(shuf -i 0-1 -n 1) # random integer, either 0 or 1
     pick_random_char $another_random_int
     password+=$random_char
 
-    pick_random_int
-    password+=$random_int
+    for (( i=0; i<5; i++ )); do
+        pick_random_int
+        password+=$random_int
+    done
 
-    pick_random_int
-    password+=$random_int
-
-    pick_random_int
-    password+=$random_int
-
-    pick_random_int
-    password+=$random_int
-
-    pick_random_int
-    password+=$random_int
-
-    pick_random_char $another_random_int
-    password+=$random_char
-
-    pick_random_char $another_random_int
-    password+=$random_char
+    for (( i=0; i<2; i++ )); do
+        local another_random_int=$(shuf -i 0-1 -n 1)
+        pick_random_char $another_random_int
+        password+=$random_char
+    done
 
     pick_random_special_char
     password+=$random_special_char
 }
 
-while getopts ":chf:" option; do
-    case ${option} in 
-        c)  # create password
-            # echo -e "\tPassword: $(date | md5sum | head -c 10)"
-            generate_password
-            echo -e "\tPassword: ${password[@]}"
+#path=$(find . -name passwords.txt)  # getting path to passwords.txt
+path="/Users/kids/Desktop/bash/passwords.txt"
+while getopts ":c:hf:ar:" option; do
+    case $option in 
+        c)  # create password            
+            if [[ ! -f "passwords.txt" ]]; then   # if cannot find passwords.txt, create and set permissions
+                touch passwords.txt
+                chmod u+r passwords.txt
+            else    # else ensure permissions are set to prevent tampering
+                chmod u+r passwords.txt # change later
+            fi
+
+            # checking for duplicate labels in passwords.txt
+            # if duplicate label found, print error
+            # else do nothing
+            case `grep "$2" passwords.txt > /dev/null; echo $?` in
+                0) # success, no duplicate labels found in file
+                    echo -e "\tError: duplicate label called '$2' found"
+                    exit 1
+                    ;;
+                1) # error, found duplicate in file
+                    generate_password
+                    echo -e "\t$2 Password: ${password[@]}"
+                    echo -e "$2,${password[@]}" >> passwords.txt   # writing password to passwords.txt
+                    ;;
+                *)
+                    echo "\tError: type unknown"
+                    exit 1
+                    ;;
+            esac
             ;;
         h)  # help     
             echo -e "\tGenerate or locate password"
@@ -78,13 +94,47 @@ while getopts ":chf:" option; do
             echo -e "\tf    Find previously generated password"
             ;;
         f)  # finding password
-            echo "finding"
+            while IFS= read -r line; do
+                if [[ "$line" == *"$2"* ]]; then
+                    current_label=$(cut -d "," -f1 <<< $line)   # gets substring before comma
+                    current_pass=$(cut -d "," -f2 <<< $line)    # gets substring after comma
+                    echo -e "\t$current_label Password: $current_pass"
+                    break
+                fi
+            done < $path
+            ;;
+        a)  # read all passwords
+            while IFS= read -r line; do
+                current_label=$(cut -d "," -f1 <<< $line)   # gets substring before comma
+                current_pass=$(cut -d "," -f2 <<< $line)    # gets substring after comma
+                printf "\t%-10s %s\n" $current_label $current_pass
+            done < $path
+            ;;
+        r) # remove label and password
+            line_count=1
+            while IFS= read -r line; do
+                if [[ "$line" == *"$2"* ]]; then
+                    sed '${line_count}d' passwords.txt
+                    line_count=$((n+line_count))  # line count
+                    break;
+                fi
+            done < path
             ;;
         *)  # default
-            echo -e "\tpassword: illegal option -- "${1:1}""
-            echo -e "\tusage: password [-c] [SEED]"
+            echo -e "\tpassword: illegal option -- "$@""
+            echo -e "\tusage: password [-c] [LABEL]"
             echo -e "\tusage: password [-hf]"
+
+            echo -e "\n\tExamples:"
+            echo -e "\tpassword -c Facebook        Generates password with 'Facebook' label"
+            echo -e "\tpassword -h                 Display help"
+            echo -e "\tpassword -f Facebook        Returns password with 'Facebook' label"
             exit 1
             ;;
         esac
 done
+
+# to do:
+# error handling for if grep fails
+# properly finding string in file
+# changing reading permissions for file
