Bug fixes and some performance testing

diff --git a/password b/password
--- a/password
+++ b/password
@@ -54,6 +54,9 @@ generate_password() {
 }
 
 path=$(find . -name passwords.txt)  # getting path to passwords.txt
+max_lines=$(wc -l < passwords.txt | awk '{ print $1 }')     # max lines of password.txt
+line_count=1
+
 while getopts ":c:hf:ar:R" option; do
     case $option in 
         c)  # create password            
@@ -86,11 +89,14 @@ while getopts ":c:hf:ar:R" option; do
         h)  # help     
             echo -e "\tGenerate or locate password"
             echo
-            echo -e "\tSyntax: password [-chfarf] [LABEL]"
+            echo -e "\tSyntax: password [-chfarR] [LABEL]"
             echo -e "\toptions:"
-            echo -e "\tc    Create password with some hash algorithm"
-            echo -e "\th    Display help page"
-            echo -e "\tf    Find previously generated password"
+            echo -e "\tc [LABEL]    Create password for [LABEL]"
+            echo -e "\th            Display help page"
+            echo -e "\tf [LABEL]    Find previously generated password for [LABEL]"
+            echo -e "\ta            Read all passwords"
+            echo -e "\tr [LABEL]    Remove password for [LABEL]"
+            echo -e "\tR            Force remove file that saves all passwords"
             ;;
         f)  # finding password
             while IFS= read -r line; do
@@ -99,7 +105,11 @@ while getopts ":c:hf:ar:R" option; do
                     current_pass=$(cut -d "," -f2 <<< $line)    # gets substring after comma
                     echo -e "\t$current_label Password: $current_pass"
                     break
+                elif [[ line_count -eq max_lines ]]; then
+                    echo -e "\tError: cannot find password for label '$2'"
+                    exit 1
                 fi
+                line_count=$((line_count+1))
             done < $path
             ;;
         a)  # read all passwords
@@ -110,8 +120,6 @@ while getopts ":c:hf:ar:R" option; do
             done < $path
             ;;
         r) # remove label and password
-            line_count=1
-            max_lines=$(wc -l < passwords.txt | awk '{ print $1 }')
             while IFS= read -r line; do
                 if [[ "$line" == *"$2"* ]]; then
                     grep -v "$line" passwords.txt > passwords_copy.txt; mv passwords_copy.txt passwords.txt
@@ -143,9 +151,9 @@ while getopts ":c:hf:ar:R" option; do
                         ;;
                 esac
             elif [[ $user_input == "n" ]]; then
-                echo -e "\tExiting..."
+                echo -e "\n\tExiting..."
             else
-                echo -e "\tError: please input valid response"
+                echo -e "\n\tError: '$user_input' is not a valid response"
                 exit 1
             fi
             ;;
@@ -162,7 +170,3 @@ while getopts ":c:hf:ar:R" option; do
             ;;
         esac
 done
-
-# to do:
-# bug fixes
-# proper error handling
