Updating master

diff --git a/password b/password
--- a/password
+++ b/password
@@ -53,6 +53,14 @@ generate_password() {
     password+=$random_special_char
 }
 
+# creating file that stores all passwords
+if [[ ! -f "passwords.txt" ]]; then   # if cannot find passwords.txt, create and set permissions
+    touch passwords.txt
+    chmod u+r passwords.txt
+else    # else ensure permissions are set to prevent tampering
+    chmod u+r passwords.txt 
+fi
+
 path=$(find . -name passwords.txt)  # getting path to passwords.txt
 max_lines=$(wc -l < passwords.txt | awk '{ print $1 }')     # max lines of password.txt
 line_count=1
@@ -60,13 +68,6 @@ line_count=1
 while getopts ":c:hf:ar:R" option; do
     case $option in 
         c)  # create password            
-            if [[ ! -f "passwords.txt" ]]; then   # if cannot find passwords.txt, create and set permissions
-                touch passwords.txt
-                chmod u+r passwords.txt
-            else    # else ensure permissions are set to prevent tampering
-                chmod u+r passwords.txt # change later
-            fi
-
             # checking for duplicate labels in passwords.txt
             # if duplicate label found, print error
             # else do nothing
@@ -138,12 +139,12 @@ while getopts ":c:hf:ar:R" option; do
             if [[ $user_input == "y" ]]; then   # if user input is yes,
                 case `find . -name 'passwords.txt' > /dev/null; echo $?` in
                     0) # cannot locate passwords.txt
-                        echo -e "\n\tError: cannot find passwords.txt"
-                        exit 1
+                        rm passwords.txt
+                        echo -e "\n\tSuccessfully removed all passwords"
                         ;;
                     1)  # successfully able to find passwords.txt
-                        rm passwords.txt
-                        echo -e "\tSuccessfully removed passwords.txt"
+                        echo -e "\n\tError: cannot find passwords.txt"
+                        exit 1
                         ;;
                     *)  # default error
                         echo -e "\tError: type unknown"
